include:
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "base.yml"
  - project: "revolutionpi/infrastructure/ci-templates"
    file: "/python/linter.yml"
  - local: debian/gitlab-ci.yml
    rules:
      - if: $CI_COMMIT_BRANCH =~ /^raspios\/.*/
      - exists:
          - debian/gitlab-ci.yml